# This is the production file for docker-compose.
# This file must be run with docker-compose -f production.yml up.
# Add the -d flag to make it execute in the background, i.e. Detached mode.

version: '3.8'

services:
  bot:
    container_name: d1vbot
    image: forsakenidol/d1vbot:1.0.0
    restart: always
    command: ["node", "src/index.js"]
    depends_on:
      - db
    env_file:
        - config.env
  db:
    container_name: discord_db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # This allows us to initialize a database from a dump on container load.
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # This specifies the configuration files.
      - ./conf.d:/etc/mysql/conf.d
    restart: always
    cap_add: 
      - SYS_NICE
    env_file:
      - db.env